[{"name": "test.test_areas_of_shapes.AreasOfShapes.test_empty", "status": "errored", "message": "", "passed": false, "points": ["p01-07.1"], "backtrace": ["  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\dpaas\\Desktop\\H3\\PythonBigData\\Opgaver_dag1\\Opgaver_dag1\\e07_areas_of_shapes\\test\\test_areas_of_shapes.py\", line 22, in test_empty\n    main()\n", "  File \"C:\\Users\\dpaas\\Desktop\\H3\\PythonBigData\\Opgaver_dag1\\Opgaver_dag1\\e07_areas_of_shapes\\src\\areas_of_shapes.py\", line 28, in main\n    input_sharpe = input(\"Choose a shape (triangle, rectangle, circle): \")\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\mock.py\", line 1134, in __call__\n    return self._mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\mock.py\", line 1138, in _mock_call\n    return self._execute_mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\mock.py\", line 1195, in _execute_mock_call\n    result = next(effect)\n             ^^^^^^^^^^^^\n"]}, {"name": "test.test_areas_of_shapes.AreasOfShapes.test_many_queries", "status": "errored", "message": "", "passed": false, "points": ["p01-07.1"], "backtrace": ["  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\dpaas\\Desktop\\H3\\PythonBigData\\Opgaver_dag1\\Opgaver_dag1\\e07_areas_of_shapes\\test\\test_areas_of_shapes.py\", line 41, in test_many_queries\n    main()\n", "  File \"C:\\Users\\dpaas\\Desktop\\H3\\PythonBigData\\Opgaver_dag1\\Opgaver_dag1\\e07_areas_of_shapes\\src\\areas_of_shapes.py\", line 28, in main\n    input_sharpe = input(\"Choose a shape (triangle, rectangle, circle): \")\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\mock.py\", line 1134, in __call__\n    return self._mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\mock.py\", line 1138, in _mock_call\n    return self._execute_mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\mock.py\", line 1195, in _execute_mock_call\n    result = next(effect)\n             ^^^^^^^^^^^^\n"]}, {"name": "test.test_areas_of_shapes.AreasOfShapes.test_one_query", "status": "errored", "message": "", "passed": false, "points": ["p01-07.1"], "backtrace": ["  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\dpaas\\Desktop\\H3\\PythonBigData\\Opgaver_dag1\\Opgaver_dag1\\e07_areas_of_shapes\\test\\test_areas_of_shapes.py\", line 29, in test_one_query\n    main()\n", "  File \"C:\\Users\\dpaas\\Desktop\\H3\\PythonBigData\\Opgaver_dag1\\Opgaver_dag1\\e07_areas_of_shapes\\src\\areas_of_shapes.py\", line 28, in main\n    input_sharpe = input(\"Choose a shape (triangle, rectangle, circle): \")\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\mock.py\", line 1134, in __call__\n    return self._mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\mock.py\", line 1138, in _mock_call\n    return self._execute_mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\mock.py\", line 1195, in _execute_mock_call\n    result = next(effect)\n             ^^^^^^^^^^^^\n"]}]